language: cpp

sudo: false

os:
  - linux
  - osx

branches:
  only:
    - master
    - test

addons:
  apt:
    packages: &common_packages
      - cmake

env:
  matrix:
    - BOGUS_JOB=true

matrix:
  exclude:
    - env: BOGUS_JOB=true

  include:
    - os: linux
      env: CXX_COMPILER=g++-5 C_COMPILER=gcc-5 CXXSTD=c++14
      addons:
        apt:
          packages:
            - *common_packages
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: CXX_COMPILER=g++-6 C_COMPILER=gcc-6 CXXSTD=c++14
      addons:
        apt:
          packages:
            - *common_packages
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      dist: trusty
      env: CXX_COMPILER=g++-7 C_COMPILER=gcc-7 CXXSTD=c++14
      addons:
        apt:
          packages:
            - *common_packages
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

    # - os: linux
    #   env: CXX_COMPILER=clang++-3.5 C_COMPILER=clang-3.5 CXXSTD="c++14"
    #   addons:
    #     apt:
    #       packages:
    #         - *common_packages
    #         - clang-3.5
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.5

    # - os: linux
    #   env: CXX_COMPILER=clang++-3.6 C_COMPILER=clang-3.6 CXXSTD="c++14"
    #   addons:
    #     apt:
    #       packages:
    #         - *common_packages
    #         - clang-3.6
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.6

    # - os: linux
    #   env: CXX_COMPILER=clang++-3.7 C_COMPILER=clang-3.7 CXXSTD="c++14"
    #   addons:
    #     apt:
    #       packages:
    #         - *common_packages
    #         - clang-3.7
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.7

    # - os: linux
    #   env: CXX_COMPILER=clang++-3.8 C_COMPILER=clang-3.8 CXXSTD="c++14"
    #   addons:
    #     apt:
    #       packages:
    #         - *common_packages
    #         - clang-3.8
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.8

    # - os: linux
    #   env: CXX_COMPILER=clang++-3.9 C_COMPILER=clang-3.9 CXXSTD="c++14"
    #   addons:
    #     apt:
    #       packages:
    #         - *common_packages
    #         - clang-3.9
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.9

    # - os: linux
    #   env: CXX_COMPILER=clang++-4.0 C_COMPILER=clang-4.0 CXXSTD="c++14"
    #   addons:
    #     apt:
    #       packages:
    #         - *common_packages
    #         - clang-4.0
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-4.0

    - os: osx
      env: CXX_COMPILER=clang++ C_COMPILER=clang CXXSTD=c++14

install:
  - cd ..
  - cd baryonyx
  - mkdir build
  - cd build
  - CXXFLAGS="-O3 -std=$CXXSTD" cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER ..

script:
  - make
  - sudo make install
  - ctest -V -R testio
  - ctest -V -R testlib
  - ctest -V -R testsolver

notifications:
  email:
    on_sucess: always
